services:
  - type: web
    name: hairlogy-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: kuafor-tk-a9bf0 # Yeni Firebase proje ID
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: ./serviceAccountKey.json
      - key: MJ_APIKEY_PUBLIC
        value: 7418d0bd58c88684f714823bc10dfe71
      - key: MJ_APIKEY_PRIVATE
        value: 6b6a9d38d193960134a4c95d31a8e174
      - key: SENDER_EMAIL
        value: noreply@hairologyyasinpremiumrandevu.com
      - key: FROM_NAME
        value: Hairlogy Yasin Premium
      - key: ADMIN_EMAIL
        value: hairlogyyasin@gmail.com
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://ollamataha_db_user:689689tk@taha.karnmcv.mongodb.net/?appName=taha
      # Firebase Service Account Key'i environment variable olarak ekleyin
      # Render Dashboard'dan "Environment" sekmesinde ekleyin
      # Key: GOOGLE_APPLICATION_CREDENTIALS_JSON
      # Value: serviceAccountKey.json dosyasının içeriği (JSON string olarak)

